# Generated by Django 4.2.1 on 2023-05-16 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_number",
                    models.CharField(default="Y8ID", max_length=4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number_of_chires", models.IntegerField()),
                ("price_of_chir", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "type_of_bus",
                    models.CharField(
                        choices=[("VIP", "VIP"), ("Noramal", "Noramal")],
                        default="Noramal",
                        max_length=10,
                    ),
                ),
                ("cancel", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frm", models.CharField(max_length=40, verbose_name="from city")),
                ("to", models.CharField(max_length=40, verbose_name="to city")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leave_at", models.DateTimeField()),
                ("arive_at", models.DateTimeField()),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passanger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus",
            name="chir_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus.chires"
            ),
        ),
    ]
