# Generated by Django 4.2.1 on 2023-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus",
            old_name="number_of_chires",
            new_name="capacity",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="chir_number",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="price_of_chir",
        ),
        migrations.AddField(
            model_name="chires",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chires",
            name="number_of_chir",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="price_of_chir",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(default="V42U", max_length=4, unique=True),
        ),
    ]
