# Generated by Django 4.2.1 on 2023-05-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0002_rename_number_of_chires_bus_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chires",
            name="trip",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="bus.trip"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(default="14EB", max_length=4, unique=True),
        ),
    ]
