# Generated by Django 4.2.1 on 2023-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0003_chires_trip_alter_bus_bus_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(default="6LI9", max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="chires",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus.trip"
            ),
        ),
    ]
