# Generated by Django 4.2.1 on 2023-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0004_alter_bus_bus_number_alter_chires_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(default="BRB2", max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="price_of_chir",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
